from typing import Any, ClassVar

class CuckooFilter:
    memory_size: ClassVar[getset_descriptor] = ...
    def __init__(self, max_key_count: int, max_kick_count: int, seed: int) -> None: ...
    def add(self, key: bytes) -> int: ...
    def contains(self, key: bytes) -> int: ...
    def contains_hash(self, fingerprint: int, h1: int) -> int: ...
    def hash(self, key: bytes) -> tuple[int, int]: ...
    def remove(self, key: bytes) -> int: ...
